---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: todo-4.07
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./manifests/4.07
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client

