name: GitOps / release todo-app (cronjob)

on:
  push:
    branches:
      - master
    paths:
      - "todo-cronjob/**"

jobs:
  build:
    name: Build and push Docker image to container registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: docker/build-push-action@v1
        with:
          repository: ahojukka5/dwk-todo-cronjob
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ github.sha }}
          path: todo-cronjob

  deploy:
    name: Edit manifest file in a GitOps manner
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up Kustomize and update kustomization.yaml
        working-directory: manifests/4.08
        run: |-
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          kustomize edit set image ahojukka5/dwk-todo-cronjob:${{ github.sha }}
      - name: Commit and push kustomization.yaml back to GitHub
        uses: EndBug/add-and-commit@v5
        with:
          add: "manifests/4.08/kustomization.yaml"
          message: New version release for todo-cronjob ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
